id: AE4241FFD
title: Various types of cloth proposed for the cīvara, but turned down
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:18:00.574867
  last_modified_at: 2022-03-01 22:18:00.574870
