id: AE4241FFD
title: CII_Jīvaka leaves Ātreya. Jīvaka’s career
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:18:00.482980
  last_modified_at: 2022-03-01 22:18:00.482984
