id: AE4241FFD
title: CII_Jīvaka and the Buddha
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:18:00.455044
  last_modified_at: 2022-03-01 22:18:00.455051
