id: AE4241FFD
title: CI_BimbisÄra kills an ascetic, who promises to be born as his son to take revenge
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:18:00.495512
  last_modified_at: 2022-03-01 22:18:00.495515
