id: AE4241FFD
title: 'Upananda aquires cloth though not invited, background in previous life: Old
  Brāhmaṇa stealthily aquirres a garment intended for the youthful Brāhmaṇa'
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:18:00.568040
  last_modified_at: 2022-03-01 22:18:00.568047
