id: AE4241FFD
title: Question on gifts by Upālin to the Lord, allowed and not
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:18:00.532380
  last_modified_at: 2022-03-01 22:18:00.532384
