id: AE4241FFD
title: CI_Khaṇḍa, the good Minister
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:18:00.509036
  last_modified_at: 2022-03-01 22:18:00.509040
