id: AE4241FFD
title: Svayaṃvara of the Haṃsarāja’s daughter
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:18:00.542981
  last_modified_at: 2022-03-01 22:18:00.542984
