id: AE4241FFD
title: Rich trader gives a great gift to a beautiful monastery, though only to one
  monk, but the Lord says this is not to be regretted
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:18:00.534050
  last_modified_at: 2022-03-01 22:18:00.534053
