id: AE4241FFD
title: Question by Upālin to the Lord on the case if a monk or somebody associated
  dies, who should take over his gear?
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:18:00.529823
  last_modified_at: 2022-03-01 22:18:00.529826
