id: AE4241FFD
title: CI_Khaṇḍa’s sons, Gopa and Siṃha
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:18:00.514037
  last_modified_at: 2022-03-01 22:18:00.514040
