id: AE4241FFD
title: CI_Khaṇḍa’s flight to Vaiśālī
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:18:00.511035
  last_modified_at: 2022-03-01 22:18:00.511038
