id: AE4241FFD
title: Prefiguration in previos life, a poisoned elephant eaten by many and a jackal,
  the previous incrnation of Upananda, is killed by a snapping bowstring
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:18:00.528352
  last_modified_at: 2022-03-01 22:18:00.528355
