id: AE4241FFD
title: CI_Biṃbisāra and Āmrapālī
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:18:00.502608
  last_modified_at: 2022-03-01 22:18:00.502612
