id: AE4241FFD
title: CII_Jīvaka returns to Rājagṛha and his vaidyarājābhiṣeka
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:18:00.491578
  last_modified_at: 2022-03-01 22:18:00.491582
