id: AE4241FFD
title: CI_Death of Bimbisāra’s First Queen, Gopa offers his niece Upacelā as Queen
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:18:00.506575
  last_modified_at: 2022-03-01 22:18:00.506581
