id: AE4241FFD
title: Upananda and previous life with two crabs, a jackal and catch of fishes
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:18:00.552648
  last_modified_at: 2022-03-01 22:18:00.552652
