id: AE4241FFD
title: Why Viśākhā’s sons were killed
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:18:00.608588
  last_modified_at: 2022-03-01 22:18:00.608592
