id: AE4241FFD
title: Upananda gets a blister on his head, gets medicines, but he dies. Principles
  for the distribution of his belongings
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:18:00.572316
  last_modified_at: 2022-03-01 22:18:00.572319
