id: AE4241FFD
title: Viśākhā’s help and advice
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:18:00.596673
  last_modified_at: 2022-03-01 22:18:00.596677
