id: AE4241FFD
title: Rules on robes
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:18:00.536960
  last_modified_at: 2022-03-01 22:18:00.536964
