id: AE4241FFD
title: CII_Birth of Jīvaka
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:18:00.330779
  last_modified_at: 2022-03-01 22:18:00.330789
