id: AE4241FFD
title: Viśākhā’s previous life
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:18:00.600498
  last_modified_at: 2022-03-01 22:18:00.600501
