id: AE4241FFD
title: CI_Biṃbisāra and the merchant’s wife
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:18:00.499741
  last_modified_at: 2022-03-01 22:18:00.499744
