id: AE4241FFD
title: CI_Vaiśālī and its gaṇa government
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:18:00.520302
  last_modified_at: 2022-03-01 22:18:00.520306
