id: AE4241FFD
title: More on sharing the deceased’s goods, Śrāvastī
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:18:00.525369
  last_modified_at: 2022-03-01 22:18:00.525372
