id: AE4241FFD
title: Viśākhā gives birth to 32 sons from eggs
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:18:00.579118
  last_modified_at: 2022-03-01 22:18:00.579121
