id: AE4241FFD
title: CII_Jīvaka chooses to train as a doctor
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:18:00.476085
  last_modified_at: 2022-03-01 22:18:00.476091
